//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthFoodArticle
    {
        public int LinkId { get; set; }
        public string Link { get; set; }
        public string LinkName { get; set; }
        public string logo { get; set; }
    }
}
