//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instruction
    {
        public int InstructionId { get; set; }
        public string InstructionText { get; set; }
        public Nullable<int> Index { get; set; }
        public int recipeId { get; set; }
    
        public virtual CookbookRecipe CookbookRecipe { get; set; }
    }
}
