//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecipezeEntities : DbContext
    {
        public RecipezeEntities()
            : base("name=RecipezeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergy> Allergies { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Instruction> Instructions { get; set; }
        public virtual DbSet<CookbookRecipe> CookbookRecipes { get; set; }
        public virtual DbSet<Substitute> Substitutes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<HealthFoodArticle> HealthFoodArticles { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
    }
}
