//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Substitute
    {
        public int AllergyId { get; set; }
        public int SubstituteId { get; set; }
        public string SubstituteName { get; set; }
        public string icon { get; set; }
    
        public virtual Allergy Allergy { get; set; }
    }
}
